version: "3"

services:
        frontend:
                build: Bookit-simple-flask-frontend/
                image: simple-flask
                networks:
                        - my_net
                        - external
                env_file:
                        - .env
                environment:
                        BACKEND_ADDR: http://backend:8080
                        DB_ADDR: db
                depends_on:
                        - db
                        - backend
                ports: 
                        - "5000:5000"
        backend:
                build: Bookit-dbManager/
                image: dbmanager
                networks:
                        - my_net
                env_file:
                        - .env
                depends_on:
                        - db
        db:
                image: postgres
                networks:
                        - my_net
                environment:
                        POSTGRES_USER: ${POSTGRES_USER:-postgres}
                        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
                        POSTGRES_DB: data

networks:
        my_net: 
                driver: bridge
                #attachable: true
        external:
                attachable: true
